platform :ios, '11.3'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'Antourage', :git => 'https://github.com/antourage/viewer-sdk-ios', :tag => 'v3.0.0-beta.3'
end

target 'PluginTests' do
  capacitor_pods
end
